kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chaindata-pvc
  labels:
    name: chaindata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name:  chaindata-pv